export const BEFORE_REQUEST_GET_LIST_PAGES = 'BEFORE_REQUEST_GET_LIST_PAGES';
export const SUCCESS_REQUEST_GET_LIST_PAGES = 'SUCCESS_REQUEST_GET_LIST_PAGES';
export const ERROR_REQUEST_GET_LIST_PAGES = 'ERROR_REQUEST_GET_LIST_PAGES';
export const FAIL_REQUEST_GET_LIST_PAGES = 'FAIL_REQUEST_GET_LIST_PAGES';

export const BEFORE_REQUEST_GET_PAGE = 'BEFORE_REQUEST_GET_PAGE';
export const SUCCESS_REQUEST_GET_PAGE = 'SUCCESS_REQUEST_GET_PAGE';
export const ERROR_REQUEST_GET_PAGE = 'ERROR_REQUEST_GET_PAGE';
export const FAIL_REQUEST_GET_PAGE = 'FAIL_REQUEST_GET_PAGE';

export const PAGEINFO_LIST_SUCCESS = 'PAGEINFO_LIST_SUCCESS';
