export const COMMON_FETCH_CONFIG_SUCCESS = 'COMMON_FETCH_CONFIG_SUCCESS';

export const BEFORE_REQUEST_UPLOAD_FILE = 'BEFORE_REQUEST_UPLOAD_FILE';
export const SUCCESS_REQUEST_UPLOAD_FILE = 'SUCCESS_REQUEST_UPLOAD_FILE';

export const COMMON_SUCCESS_REQUEST_LIST_FOOTER_PAGE = 'COMMON_SUCCESS_REQUEST_LIST_FOOTER_PAGE';

export const COMMON_SET_KEYCLOAK = 'COMMON_SET_KEYCLOAK';

export const SUCCESS_GET_MA_NOTICE = 'SUCCESS_GET_MA_NOTICE';
export const SUCCESS_REQUEST_GET_MY_NOTICE = 'SUCCESS_REQUEST_GET_MY_NOTICE';

export const SUCCESS_REQUEST_ISREAD = 'SUCCESS_REQUEST_ISREAD';
export const SUCCESS_REQUEST_RESETBAGGY = 'SUCCESS_REQUEST_RESETBAGGY';
export const SUCCESS_REQUEST_RESET_READ = 'SUCCESS_REQUEST_RESET_READ';
export const NOTIFY_INCREMENT = 'NOTIFY_INCREMENT';
export const NOTIFY_GET_DATAPUSH = 'NOTIFY_GET_DATAPUSH';
export const NOTIFY_PUSH_DEVICE_TOKEN = 'NOTIFY_PUSH_DEVICE_TOKEN';

export const COMMON_SEO_SUCCESS = 'COMMON_SEO_SUCCESS';
export const NOTIFY_MANUAL_COUNT = 'NOTIFY_MANUAL_COUNT';
export const NOTIFY_MANUAL_RESET = 'NOTIFY_MANUAL_RESET';

export const SUCCESS_REQUEST_GET_MY_NOTICE_DETAIL = 'SUCCESS_REQUEST_GET_MY_NOTICE_DETAIL';
