export const COMMENT_SUCCESS_FETCH_LIST_COMMENT = 'COMMENT_SUCCESS_FETCH_LIST_COMMENT';

export const COMMENT_SUCCESS_CREATE_BY_COURSE = 'COMMENT_SUCCESS_CREATE_BY_COURSE';

export const COMMENT_SUCCESS_REPLY_BY_COURSE = 'COMMENT_SUCCESS_REPLY_BY_COURSE';
