export const BEFORE_REQUEST_MY_GIFT = 'BEFORE_REQUEST_MY_GIFT';
export const SUCCESS_REQUEST_MY_GIFT = 'SUCCESS_REQUEST_MY_GIFT';
export const ERROR_REQUEST_MY_GIFT = 'ERROR_REQUEST_MY_GIFT';
export const FAIL_REQUEST_MY_GIFT = 'FAIL_REQUEST_MY_GIFT';

export const BEFORE_REQUEST_REDEEM_GIFTCODE = 'BEFORE_REQUEST_REDEEM_GIFTCODE';
export const SUCCESS_REQUEST_REDEEM_GIFTCODE = 'SUCCESS_REQUEST_REDEEM_GIFTCODE';
export const ERROR_REQUEST_REDEEM_GIFTCODE = 'ERROR_REQUEST_REDEEM_GIFTCODE';
export const FAIL_REQUEST_REDEEM_GIFTCODE = 'FAIL_REQUEST_REDEEM_GIFTCODE';
