export const USER_DETAIL_SUCCESS = 'USER_DETAIL_SUCCESS';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const COMMISSION_FETCH_LIST_SUCCESS = 'COMMISSION_FETCH_LIST_SUCCESS';
export const PROCESS_CHART_GET_SUCCESS = 'PROCESS_CHART_GET_SUCCESS';
export const REPORT_HISTORY_GET_SUCCESS = 'REPORT_HISTORY_GET_SUCCESS';
export const REPORT_COURSE_HISTORY_GET_SUCCESS = 'REPORT_COURSE_HISTORY_GET_SUCCESS';
