export const COURSE_FETCH_LIST_SUCCESS = 'COURSE_FETCH_LIST_SUCCESS';
export const FETCH_COURSE_DETAIL_SUCCESS = 'FETCH_COURSE_DETAIL_SUCCESS';
export const FETCH_LESSON_DETAIL_SUCCESS = 'FETCH_LESSON_DETAIL_SUCCESS';
export const LOG_LESSON_SUCCESS = 'LOG_LESSON_SUCCESS';

export const COMBOS_FETCH_LIST_SUCCESS = 'COMBOS_FETCH_LIST_SUCCESS';
export const FETCH_COMBO_DETAIL_SUCCESS = 'FETCH_COMBO_DETAIL_SUCCESS';
export const TEACHER_COURSES_SUCCESS = 'TEACHER_COURSES_SUCCESS';
