export const BEFORE_REQUEST_ACTIVECODE = 'BEFORE_REQUEST_ACTIVECODE';
export const SUCCESS_REQUEST_ACTIVECODE = 'SUCCESS_REQUEST_ACTIVECODE';
export const ERROR_REQUEST_ACTIVECODE = 'ERROR_REQUEST_ACTIVECODE';
export const FAIL_REQUEST_ACTIVECODE = 'FAIL_REQUEST_ACTIVECODE';

export const BEFORE_REQUEST_MY_COURSE = 'BEFORE_REQUEST_MY_COURSE';
export const SUCCESS_REQUEST_MY_COURSE = 'SUCCESS_REQUEST_MY_COURSE';
export const ERROR_REQUEST_MY_COURSE = 'ERROR_REQUEST_MY_COURSE';
export const FAIL_REQUEST_MY_COURSE = 'FAIL_REQUEST_MY_COURSE';

export const BEFORE_REQUEST_GET_COURSE = 'BEFORE_REQUEST_GET_COURSE';
export const SUCCESS_REQUEST_GET_COURSE = 'SUCCESS_REQUEST_GET_COURSE';
export const ERROR_REQUEST_GET_COURSE = 'ERROR_REQUEST_GET_COURSE';
export const FAIL_REQUEST_GET_COURSE = 'FAIL_REQUEST_GET_COURSE';

export const SUCCESS_REQUEST_CREATE_ORDER = 'SUCCESS_REQUEST_CREATE_ORDER';
export const ERROR_REQUEST_CREATE_ORDER = 'ERROR_REQUEST_CREATE_ORDER';
export const FAIL_REQUEST_CREATE_ORDER = 'FAIL_REQUEST_CREATE_ORDER';

export const SUCCESS_REQUEST_GET_ORDER_HISTORY = 'SUCCESS_REQUEST_GET_ORDER_HISTORY';
export const ERROR_REQUEST_GET_ORDER_HISTORY = 'ERROR_REQUEST_GET_ORDER_HISTORY';
export const FAIL_REQUEST_GET_ORDER_HISTORY = 'FAIL_REQUEST_GET_ORDER_HISTORY';

export const SUCCESS_REQUEST_UPDATE_ORDER = 'SUCCESS_REQUEST_UPDATE_ORDER';
export const ERROR_REQUEST_UPDATE_ORDER = 'ERROR_REQUEST_UPDATE_ORDER';
export const FAIL_REQUEST_UPDATE_ORDER = 'FAIL_REQUEST_UPDATE_ORDER';

export const CLEAR_ORDER = 'CLEAR_ORDER';

export const SUCCESS_REQUEST_GET_ORDER_HISTORIES = 'SUCCESS_REQUEST_GET_ORDER_HISTORIES';
export const ERROR_REQUEST_GET_ORDER_HISTORIES = 'ERROR_REQUEST_GET_ORDER_HISTORIES';
export const FAIL_REQUEST_GET_ORDER_HISTORIES = 'FAIL_REQUEST_GET_ORDER_HISTORIES';

export const BEFORE_REQUEST_GET_INFO_ORDER = 'BEFORE_REQUEST_GET_INFO_ORDER';
export const SUCCESS_REQUEST_GET_INFO_ORDER = 'SUCCESS_REQUEST_GET_INFO_ORDER';
export const ERROR_REQUEST_GET_INFO_ORDER = 'ERROR_REQUEST_GET_INFO_ORDER';
export const FAIL_REQUEST_GET_INFO_ORDER = 'FAIL_REQUEST_GET_INFO_ORDER';

export const BEFORE_REQUEST_CHECK_ORDER = 'BEFORE_REQUEST_CHECK_ORDER';
export const SUCCESS_REQUEST_CHECK_ORDER = 'SUCCESS_REQUEST_CHECK_ORDER';
export const ERROR_REQUEST_CHECK_ORDER = 'ERROR_REQUEST_CHECK_ORDER';
export const FAIL_REQUEST_CHECK_ORDER = 'FAIL_REQUEST_CHECK_ORDER';

export const BEFORE_REQUEST_CHECK_COUPON = 'BEFORE_REQUEST_CHECK_COUPON';
export const SUCCESS_REQUEST_CHECK_COUPON = 'SUCCESS_REQUEST_CHECK_COUPON';
export const ERROR_REQUEST_CHECK_COUPON = 'ERROR_REQUEST_CHECK_COUPON';
export const FAIL_REQUEST_CHECK_COUPON = 'FAIL_REQUEST_CHECK_COUPON';
