export const CATEGORY_TOP_SUCCESS = 'CATEGORY_TOP_SUCCESS';
export const CATEGORY_HIGHTLIGHT_SUCCESS = 'CATEGORY_HIGHTLIGHT_SUCCESS';
export const CATEGORY_LIST_SUCCESS = 'CATEGORY_LIST_SUCCESS';

export const CATEGORY_SUCCESS_FETCH_LIST_MENU = 'CATEGORY_SUCCESS_FETCH_LIST_MENU';
export const INFO_CATEGORY_SUCCESS = 'INFO_CATEGORY_SUCCESS';
