export const BEFORE_REQUEST_GET_LIST_NEWSLETTERS = 'BEFORE_REQUEST_GET_LIST_NEWSLETTERS';
export const SUCCESS_REQUEST_GET_LIST_NEWSLETTERS = 'SUCCESS_REQUEST_GET_LIST_NEWSLETTERS';
export const ERROR_REQUEST_GET_LIST_NEWSLETTERS = 'ERROR_REQUEST_GET_LIST_NEWSLETTERS';
export const FAIL_REQUEST_GET_LIST_NEWSLETTERS = 'FAIL_REQUEST_GET_LIST_NEWSLETTERS';

export const BEFORE_REQUEST_GET_NEWSLETTER = 'BEFORE_REQUEST_GET_NEWSLETTER';
export const SUCCESS_REQUEST_GET_NEWSLETTER = 'SUCCESS_REQUEST_GET_NEWSLETTER';
export const ERROR_REQUEST_GET_NEWSLETTER = 'ERROR_REQUEST_GET_NEWSLETTER';
export const FAIL_REQUEST_GET_NEWSLETTER = 'FAIL_REQUEST_GET_NEWSLETTER';

export const SUCCESS_REQUEST_CREATE_NEWSLETTER = 'SUCCESS_REQUEST_CREATE_NEWSLETTER';
export const ERROR_REQUEST_CREATE_NEWSLETTER = 'ERROR_REQUEST_CREATE_NEWSLETTER';
export const FAIL_REQUEST_CREATE_NEWSLETTER = 'FAIL_REQUEST_CREATE_NEWSLETTER';
