export const BEFORE_REQUEST_LOGIN = 'BEFORE_REQUEST_LOGIN';
export const SUCCESS_REQUEST_LOGIN = 'SUCCESS_REQUEST_LOGIN';
export const ERROR_REQUEST_LOGIN = 'ERROR_REQUEST_LOGIN';
export const FAIL_REQUEST_LOGIN = 'FAIL_REQUEST_LOGIN';

export const BEFORE_REQUEST_LOGOUT = 'BEFORE_REQUEST_LOGOUT';
export const SUCCESS_REQUEST_LOGOUT = 'SUCCESS_REQUEST_LOGOUT';
export const ERROR_REQUEST_LOGOUT = 'ERROR_REQUEST_LOGOUT';
export const FAIL_REQUEST_LOGOUT = 'FAIL_REQUEST_LOGOUT';

export const BEFORE_REQUEST_ME = 'BEFORE_REQUEST_ME';
export const SUCCESS_REQUEST_ME = 'SUCCESS_REQUEST_ME';
export const ERROR_REQUEST_ME = 'ERROR_REQUEST_ME';
export const FAIL_REQUEST_ME = 'FAIL_REQUEST_ME';

export const TOGGLE_FULL_PERMISSION = 'TOGGLE_FULL_PERMISSION';

export const RESET_LOGOUT_REQUEST = 'RESET_LOGOUT_REQUEST';

export const BEFORE_REQUEST_REFRESH_TOKEN = 'BEFORE_REQUEST_REFRESH_TOKEN';
export const SUCCESS_REQUEST_REFRESH_TOKEN = 'SUCCESS_REQUEST_REFRESH_TOKEN';
export const ERROR_REQUEST_REFRESH_TOKEN = 'ERROR_REQUEST_REFRESH_TOKEN';

export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';

export const SUCCESS_REQUEST_MY_COURSES = 'SUCCESS_REQUEST_MY_COURSES';
export const ERROR_REQUEST_MY_COURSES = 'ERROR_REQUEST_MY_COURSES';
export const FAIL_REQUEST_MY_COURSES = 'FAIL_REQUEST_MY_COURSES';

export const AUTH_SET_USER_LOGIN = 'AUTH_SET_USER_LOGIN';

export const USER_COURSE_FETCH_LIST_SUCCESS = 'USER_COURSE_FETCH_LIST_SUCCESS';
export const USER_COURSE_FETCH_LIST_ERROR = 'USER_COURSE_FETCH_LIST_ERROR';
export const USER_COURSE_FETCH_LIST_FAIL = 'USER_COURSE_FETCH_LIST_FAIL';

export const CHANGE_PASS_SUCCESS = 'CHANGE_PASS_SUCCESS';
export const CHANGE_PASS_ERROR = 'CHANGE_PASS_ERROR';
export const CHANGE_PASS_FAIL = 'CHANGE_PASS_FAIL';
