export const PB_COMMON = 'PB_COMMON';
export const PB_DO_ACTION = 'PB_DO_ACTION';

export const PB_CHANGE_PROPS_ACTION = 'PB_CHANGE_PROPS_ACTION';
export const PB_CHANGE_LABEL_ACTION = 'PB_CHANGE_LABEL_ACTION';
export const PB_REMOVE_ELEMENT_ACTION = 'PB_REMOVE_ELEMENT_ACTION';

export const PB_OPEN_ELEMENT_MENU_ACTION = 'PB_OPEN_ELEMENT_MENU_ACTION';
export const PB_CLOSE_ELEMENT_MENU_ACTION = 'PB_CLOSE_ELEMENT_MENU_ACTION';
export const PB_TOGGLE_CATEGORY_ACTION = 'PB_TOGGLE_CATEGORY_ACTION';
export const PB_ADD_ELEMENT_AT_ACTION = 'PB_ADD_ELEMENT_AT_ACTION';

export const PB_CHANGE_ELEMENT_CONTENT_ACTION = 'PB_CHANGE_ELEMENT_CONTENT_ACTION';
export const PB_CHANGE_DOC_PROPERTY_ACTION = 'PB_CHANGE_DOC_PROPERTY_ACTION';

export const PB_TOGGLE_EDITING_ACTION = 'PB_TOGGLE_EDITING_ACTION';

export const PB_ON_CHANGE_PAGE_BUILDER_ACTION = 'PB_ON_CHANGE_PAGE_BUILDER_ACTION';

export const PB_ON_CHANGE_LAYOUT_BUILDER_ACTION = 'PB_ON_CHANGE_LAYOUT_BUILDER_ACTION';

export const PB_ON_CHANGE_TITLE_PAGE_ACTION = 'PB_ON_CHANGE_TITLE_PAGE_ACTION';
export const PB_ON_CHANGE_ROUTE_PAGE_ACTION = 'PB_ON_CHANGE_ROUTE_PAGE_ACTION';

export const PB_SET_MENU_TAB_ACTION = 'PB_SET_MENU_TAB_ACTION';

export const PB_SELECT_ELEMENT = 'PB_SELECT_ELEMENT';
export const PB_OUT_ELEMENT = 'PB_OUT_ELEMENT';
export const PB_OVER_ELEMENT = 'PB_OVER_ELEMENT';

export const PB_GET_PAGE_DATA_BY_ID = 'PB_GET_PAGE_DATA_BY_ID';

export const PB_GET_LIST_PAGE_BUILDER_SUCCESS = 'PB_GET_LIST_PAGE_BUILDER_SUCCESS';
