export const BEFORE_REQUEST_GET_LIST_SETTINGS = 'BEFORE_REQUEST_GET_LIST_SETTINGS';
export const SUCCESS_REQUEST_GET_LIST_SETTINGS = 'SUCCESS_REQUEST_GET_LIST_SETTINGS';
export const ERROR_REQUEST_GET_LIST_SETTINGS = 'ERROR_REQUEST_GET_LIST_SETTINGS';
export const FAIL_REQUEST_GET_LIST_SETTINGS = 'FAIL_REQUEST_GET_LIST_SETTINGS';

export const BEFORE_REQUEST_GET_SETTING = 'BEFORE_REQUEST_GET_SETTING';
export const SUCCESS_REQUEST_GET_SETTING = 'SUCCESS_REQUEST_GET_SETTING';
export const ERROR_REQUEST_GET_SETTING = 'ERROR_REQUEST_GET_SETTING';
export const FAIL_REQUEST_GET_SETTING = 'FAIL_REQUEST_GET_SETTING';
