export const RATING_SUCCESS_FETCH_DATA_BY_COURSE = 'RATING_SUCCESS_FETCH_DATA_BY_COURSE';

export const RATING_SUCCESS_FETCH_LIST_BY_COURSE = 'RATING_SUCCESS_FETCH_LIST_BY_COURSE';

export const RATING_SUCCESS_RATING_BY_COURSE = 'RATING_SUCCESS_RATING_BY_COURSE';
