export const SUCCESS_FETCH_WIDGET_ROUTE_LIST = 'SUCCESS_FETCH_WIDGET_ROUTE_LIST';

export const BEFORE_FETCH_WIDGET_FIELD_LIST = 'BEFORE_FETCH_WIDGET_FIELD_LIST';
export const SUCCESS_FETCH_WIDGET_FIELD_LIST = 'SUCCESS_FETCH_WIDGET_FIELD_LIST';
export const ERROR_FETCH_WIDGET_FIELD_LIST = 'ERROR_FETCH_WIDGET_FIELD_LIST';

export const SUCCESS_FETCH_WIDGET_FEATURED_TOPIC = 'SUCCESS_FETCH_WIDGET_FEATURED_TOPIC';
export const ERROR_FETCH_WIDGET_FEATURED_TOPIC = 'ERROR_FETCH_WIDGET_FEATURED_TOPIC';

export const SUCCESS_FETCH_WIDGET_CATEGORY_HIGHLIGHS = 'SUCCESS_FETCH_WIDGET_CATEGORY_HIGHLIGHS';
export const ERROR_FETCH_WIDGET_CATEGORY_HIGHLIGHS = 'ERROR_FETCH_WIDGET_CATEGORY_HIGHLIGHS';

export const SUCCESS_FETCH_WIDGET_COUPON_COURSE = 'SUCCESS_FETCH_WIDGET_COUPON_COURSE';
export const ERROR_FETCH_WIDGET_COUPON_COURSE = 'ERROR_FETCH_WIDGET_COUPON_COURSE';

export const SUCCESS_FETCH_WIDGET_SLIDER_COURSE_NEW = 'SUCCESS_FETCH_WIDGET_SLIDER_COURSE_NEW';
export const ERROR_FETCH_WIDGET_SLIDER_COURSE_NEW = 'ERROR_FETCH_WIDGET_SLIDER_COURSE_NEW';

export const SUCCESS_FETCH_WIDGET_SLIDER_COURSE_HIGHLIGHTS = 'SUCCESS_FETCH_WIDGET_SLIDER_COURSE_HIGHLIGHTS';
export const ERROR_FETCH_WIDGET_SLIDER_COURSE_HIGHLIGHTS = 'ERROR_FETCH_WIDGET_SLIDER_COURSE_HIGHLIGHTS';

export const SUCCESS_FETCH_WIDGET_SLIDER_COURSE_SALE = 'SUCCESS_FETCH_WIDGET_SLIDER_COURSE_SALE';
export const ERROR_FETCH_WIDGET_SLIDER_COURSE_SALE = 'ERROR_FETCH_WIDGET_SLIDER_COURSE_SALE';

export const SUCCESS_FETCH_WIDGET_DISCOUNT_COURSE = 'SUCCESS_FETCH_WIDGET_DISCOUNT_COURSE';
export const ERROR_FETCH_WIDGET_DISCOUNT_COURSE = 'ERROR_FETCH_WIDGET_DISCOUNT_COURSE';

export const SUCCESS_FETCH_WIDGET_GIFTCODE_COURSE = 'SUCCESS_FETCH_WIDGET_GIFTCODE_COURSE';
export const ERROR_FETCH_WIDGET_GIFTCODE_COURSE = 'ERROR_FETCH_WIDGET_GIFTCODE_COURSE';
